[redhat] Makefile: new dist-buildreq-check target
Add a new dist-buildreq-check target that checks for missing
packages via rpmspec -q --buildrequires, and make dist-configs-prep
dependent on it.

This change is based on suggestions from Josh Poimboeuf, Don Zickus,
and Herton Krzesinski.  Ultimately this is Herton's version, which
generates the list of missing packages from an already-created
kernel.spec file.

Signed-off-by: Ben Crocker <bcrocker@redhat.com>

diff --git a/redhat/Makefile b/redhat/Makefile
--- a/redhat/Makefile
+++ b/redhat/Makefile
@@ -144,7 +144,7 @@ rh-configs: dist-configs
 dist-configs-check: dist-configs-prep
 	cd $(REDHAT)/configs; ./process_configs.sh $(PROCESS_CONFIGS_CHECK_OPTS) $(PACKAGE_NAME)
 
-dist-configs-prep: dist-clean-configs
+dist-configs-prep: dist-clean-configs dist-buildreq-check
 	cd $(REDHAT)/configs; ./build_configs.sh "$(PACKAGE_NAME)" "$(ARCH_MACH)" "$(FLAVOR)"
 
 dist-configs-arch: ARCH_MACH = $(MACH)
@@ -207,6 +207,17 @@ dist-git-version-check:
 	IFS=; \
 	if [ "$$3" -lt 2 -o \( "$$3" -eq 2 -a "$$4" -lt 13 \) ]; then \
 		echo "ERROR: You need git version 2.13 or newer to run some setup commands"; \
+		exit 1; \
+	fi
+
+dist-buildreq-check: setup-source
+	@PKGLIST="rpm-build $(rpmspec -q --buildrequires $(SOURCES)/$(SPECFILE) | cut -d ' ' -f 1)"; \
+	MISSING=""; \
+	for pkg in $$PKGLIST; do \
+		rpm -q --whatprovides $$pkg >/dev/null || MISSING="$$MISSING $$pkg"; \
+	done; \
+	if [ -n "$$MISSING" ]; then \
+		echo "Error: please install $$MISSING"; \
 		exit 1; \
 	fi
 
@@ -522,6 +533,7 @@ dist-full-help:
 
 	@echo  ''
 	@echo  'Misc targets:'
+	@echo  '  dist-buildreq-check - Checks for presence of packages required for build'
 	@echo  '  dist-get-latest - Returns the latest "known good" kernel from brew. This'
 	@echo  '                    should not be confused with the latest top-of-tree'
 	@echo  '                    development tag.'
